# acl.auth.php
# <?php exit()?>
# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 31 Dec 2016 09:45:21 +0000
*	@ALL	0
*	@user	1
sidebar	wuyonghong	2
sidebar	@ALL	0
sidebar	@user	0
1.公司资料:test	@user	0
1.公司资料:1.3redmine:test	wuyonghong	0
1.公司资料:1.3redmine:test	@user	0
1.公司资料:1.2公司流程:test	@user	0
2.项目资料:2.1聚合平台:2.1.1安卓聚合平台:test	@user	0
2.项目资料:2.1聚合平台:2.1.2ios聚合平台:test	@user	0
2.项目资料:2.1聚合平台:2.1.3H5聚合平台:test	@user	0
2.项目资料:2.2运营平台:2.2.1安卓运营平台:test	@user	0
2.项目资料:2.2运营平台:2.2.2IOS切换运营平台:test	@user	0
2.项目资料:2.2运营平台:2.2.3IOS免越狱运营平台:test	@user	0
2.项目资料:2.2运营平台:2.2.4H5运营平台:test	@user	0
2.项目资料:2.3打包平台:2.3.1安卓打包平台:test	@user	0
2.项目资料:2.3打包平台:2.3.2IOS打包平台:test	@user	0
2.项目资料:2.3打包平台:2.3.3H5打包平台:test	@user	0
2.项目资料:2.4游戏:2.4.1坦克:test	@user	0
2.项目资料:2.5多级分销平台:2.5.1呗宝:test	@user	0
2.项目资料:2.6销售官网:2.6.1学习库:test	@user	0
2.项目资料:2.7其他:2.7.1OA:test	@user	0
2.项目资料:2.7其他:2.7.2王者带练:test	@user	0
2.项目资料:2.7其他:2.7.3信用积分:test	@user	0
3.学习资料:3.1PHP:test	@user	0
3.学习资料:3.2JAVA:test	@user	0
3.学习资料:3.3LINUX:test	@user	0
3.学习资料:3.4WEB/JS/CSS:test	@user	0
4.其他:test	@user	0
