<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: wuyonghong
 * Date: Tue, 20 Mar 2018 11:44:35 +0800
 */

$conf['title'] = '火速文档中心';
$conf['tagline'] = '火树学习文档中心';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['typography'] = '0';
$conf['maxtoclevel'] = '5';
$conf['useheading'] = 'content';
$conf['relnofollow'] = 0;
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['mediarevisions'] = 0;
$conf['updatecheck'] = 0;
$conf['canonical'] = 1;
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '<b>cXlsMjM1MDE1Nw==';
$conf['plugin']['discussion']['automatic'] = 1;
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['showguests'] = 0;
$conf['plugin']['discussion']['useavatar'] = 0;
$conf['plugin']['addnewpage']['addpage_hideACL'] = 1;
$conf['plugin']['smtp']['smtp_host'] = 'smtp.huosdk.com';
$conf['plugin']['smtp']['auth_user'] = 'redmine@huosdk.com';
$conf['plugin']['smtp']['auth_pass'] = 'Redmine@2016';
$conf['plugin']['smtp']['debug'] = 1;
$conf['tpl']['bootstrap3']['fixedTopNavbar'] = '1';
$conf['tpl']['vector']['vector_donate_url'] = 'http://www.wangzhanmeng.com';

// end auto-generated content
